# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

SalaryComJob.create(:title => "Media Production Manager" , :code => "AR17000025")
SalaryComJob.create(:title => "Production Manager" , :code => "AR17000025")
SalaryComJob.create(:title => "Exhibit Designer - Museum" , :code => "AR17000027")
SalaryComJob.create(:title => "Exhibition Designer - Museum" , :code => "AR17000027")
SalaryComJob.create(:title => "Museum Exhibit Designer" , :code => "AR17000027")
SalaryComJob.create(:title => "Education Specialist - Museum" , :code => "AR17000028")
SalaryComJob.create(:title => "Museum Education Program Specialist" , :code => "AR17000028")
SalaryComJob.create(:title => "Museum Education Specialist" , :code => "AR17000028")
SalaryComJob.create(:title => "Development Associate - Museum " , :code => "AR17000029")
SalaryComJob.create(:title => "Museum Business Development Associate" , :code => "AR17000029")
SalaryComJob.create(:title => "Museum Development Associate" , :code => "AR17000029")
SalaryComJob.create(:title => "Membership Associate - Museum " , :code => "AR17000030")
SalaryComJob.create(:title => "Museum Membership Associate" , :code => "AR17000030")
SalaryComJob.create(:title => "Entry Level Technical Writer" , :code => "CM02000001")
SalaryComJob.create(:title => "Level I Technical Writer" , :code => "CM02000001")
SalaryComJob.create(:title => "Technical Writer I" , :code => "CM02000001")
SalaryComJob.create(:title => "Intermediate Level Technical Writer" , :code => "CM02000002")
SalaryComJob.create(:title => "Level II Technical Writer" , :code => "CM02000002")
SalaryComJob.create(:title => "Technical Writer II" , :code => "CM02000002")
SalaryComJob.create(:title => "Level III Technical Writer" , :code => "CM02000003")
SalaryComJob.create(:title => "Senior Technical Writer" , :code => "CM02000003")
SalaryComJob.create(:title => "Technical Writer III" , :code => "CM02000003")
SalaryComJob.create(:title => "Engineering Illustrator" , :code => "CM02000004")
SalaryComJob.create(:title => "Production Illustrator" , :code => "CM02000004")
SalaryComJob.create(:title => "Technical Illustrator" , :code => "CM02000004")
SalaryComJob.create(:title => "Grant Proposal Writer" , :code => "CM02000005")
SalaryComJob.create(:title => "Grants/Proposal Writer" , :code => "CM02000005")
SalaryComJob.create(:title => "Entry Level Public Relations Specialist" , :code => "CM02000006")
SalaryComJob.create(:title => "Level I Public Relations Specialist" , :code => "CM02000006")
SalaryComJob.create(:title => "Public Relations Specialist I" , :code => "CM02000006")
SalaryComJob.create(:title => "Intermediate Level Public Relations Specialist" , :code => "CM02000007")
SalaryComJob.create(:title => "Level II Public Relations Specialist" , :code => "CM02000007")
SalaryComJob.create(:title => "Public Relations Specialist II" , :code => "CM02000007")
SalaryComJob.create(:title => "Level III Public Relations Specialist" , :code => "CM02000008")
SalaryComJob.create(:title => "Public Relations Specialist III" , :code => "CM02000008")
SalaryComJob.create(:title => "Senior Public Relations Specialist" , :code => "CM02000008")
SalaryComJob.create(:title => "Editor" , :code => "CM02000009")
SalaryComJob.create(:title => "Senior Editor" , :code => "CM02000010")
SalaryComJob.create(:title => "Speech Writer" , :code => "CM02000011")
SalaryComJob.create(:title => "CopyWriter I" , :code => "CM02000012")
SalaryComJob.create(:title => "Entry Level CopyWriter" , :code => "CM02000012")
SalaryComJob.create(:title => "Level I CopyWriter" , :code => "CM02000012")
SalaryComJob.create(:title => "CopyWriter II" , :code => "CM02000013")
SalaryComJob.create(:title => "Intermediate Level CopyWriter" , :code => "CM02000013")
SalaryComJob.create(:title => "Level II CopyWriter" , :code => "CM02000013")
SalaryComJob.create(:title => "CopyWriter III" , :code => "CM02000014")
SalaryComJob.create(:title => "Level III CopyWriter" , :code => "CM02000014")
SalaryComJob.create(:title => "Senior CopyWriter" , :code => "CM02000014")
SalaryComJob.create(:title => "PR Manager" , :code => "CM02000015")
SalaryComJob.create(:title => "Public Relations Manager" , :code => "CM02000015")
SalaryComJob.create(:title => "Photographer" , :code => "CM02000016")
SalaryComJob.create(:title => "Artist" , :code => "CM02000017")
SalaryComJob.create(:title => "Graphic Design Specialist" , :code => "CM02000018")
SalaryComJob.create(:title => "Senior Graphic Design Specialist" , :code => "CM02000019")
SalaryComJob.create(:title => "Senior Graphic Designer" , :code => "CM02000019")
SalaryComJob.create(:title => "Audio Visual Technician" , :code => "CM02000020")
SalaryComJob.create(:title => "AV Technician" , :code => "CM02000020")
SalaryComJob.create(:title => "Correspondent" , :code => "CM02000021")
SalaryComJob.create(:title => "Intermediate Level Reporter" , :code => "CM02000021")
SalaryComJob.create(:title => "Journalist II" , :code => "CM02000021")
SalaryComJob.create(:title => "Level II Reporter" , :code => "CM02000021")
SalaryComJob.create(:title => "Newsperson II" , :code => "CM02000021")
SalaryComJob.create(:title => "Reporter II" , :code => "CM02000021")
SalaryComJob.create(:title => "Broadcast Technician" , :code => "CM02000022")
SalaryComJob.create(:title => "Broadcast Technician (TV/Radio)" , :code => "CM02000022")
SalaryComJob.create(:title => "Animator/Cartoonist" , :code => "CM02000023")
SalaryComJob.create(:title => "Cartoonist / Animator" , :code => "CM02000023")
SalaryComJob.create(:title => "Cartoonists & Animators" , :code => "CM02000023")
SalaryComJob.create(:title => "Cartoonists and Animators" , :code => "CM02000023")
SalaryComJob.create(:title => "Communications Manager" , :code => "CM02000024")
SalaryComJob.create(:title => "Proofreader" , :code => "CM02000026")
SalaryComJob.create(:title => "Engraving Operator" , :code => "CM02000027")
SalaryComJob.create(:title => "Photoengraver" , :code => "CM02000027")
SalaryComJob.create(:title => "Photolith Operator" , :code => "CM02000027")
SalaryComJob.create(:title => "Medical Illustrator" , :code => "CM02000028")
SalaryComJob.create(:title => "Scientific Artist" , :code => "CM02000028")
SalaryComJob.create(:title => "Scientific Illustrator" , :code => "CM02000028")
SalaryComJob.create(:title => "Scientific/Medical Illustrator" , :code => "CM02000028")
SalaryComJob.create(:title => "Checker" , :code => "CM02000030")
SalaryComJob.create(:title => "Photo Checker Assembler" , :code => "CM02000030")
SalaryComJob.create(:title => "Director of Public Relations" , :code => "CM02000031")
SalaryComJob.create(:title => "PR Director" , :code => "CM02000031")
SalaryComJob.create(:title => "Public Relations Director" , :code => "CM02000031")
SalaryComJob.create(:title => "Media Supervisor" , :code => "CM02000034")
SalaryComJob.create(:title => "Media Coordinator" , :code => "CM02000035")
SalaryComJob.create(:title => "Media Director" , :code => "CM02000036")
SalaryComJob.create(:title => "Multimedia Services Manager" , :code => "CM02000038")
SalaryComJob.create(:title => "Entry Level Reporter" , :code => "CM02000039")
SalaryComJob.create(:title => "Journalist I" , :code => "CM02000039")
SalaryComJob.create(:title => "Level I Reporter" , :code => "CM02000039")
SalaryComJob.create(:title => "Newsperson I" , :code => "CM02000039")
SalaryComJob.create(:title => "Reporter I" , :code => "CM02000039")
SalaryComJob.create(:title => "Journalist III" , :code => "CM02000040")
SalaryComJob.create(:title => "Level III Reporter" , :code => "CM02000040")
SalaryComJob.create(:title => "Newsperson III" , :code => "CM02000040")
SalaryComJob.create(:title => "Reporter III" , :code => "CM02000040")
SalaryComJob.create(:title => "Senior Reporter" , :code => "CM02000040")
SalaryComJob.create(:title => "CopyWriter - Project Lead" , :code => "CM02000041")
SalaryComJob.create(:title => "CopyWriter IV" , :code => "CM02000041")
SalaryComJob.create(:title => "Level IV CopyWriter" , :code => "CM02000041")
SalaryComJob.create(:title => "Level IV Public Relations Specialist" , :code => "CM02000042")
SalaryComJob.create(:title => "Public Relations Specialist - Project Lead" , :code => "CM02000042")
SalaryComJob.create(:title => "Public Relations Specialist IV" , :code => "CM02000042")
SalaryComJob.create(:title => "Level IV Technical Writer" , :code => "CM02000043")
SalaryComJob.create(:title => "Technical Writer - Project Lead" , :code => "CM02000043")
SalaryComJob.create(:title => "Technical Writer IV" , :code => "CM02000043")
SalaryComJob.create(:title => "Manager of Operations" , :code => "CM02000044")
SalaryComJob.create(:title => "Media Operations Manager" , :code => "CM02000044")
SalaryComJob.create(:title => "Operations Manager" , :code => "CM02000044")
SalaryComJob.create(:title => "Arts/Entertainment Producer" , :code => "CM02000045")
SalaryComJob.create(:title => "Producer" , :code => "CM02000045")
SalaryComJob.create(:title => "Production Assistant" , :code => "CM02000046")
SalaryComJob.create(:title => "Production Associate" , :code => "CM02000046")
SalaryComJob.create(:title => "Media Program Director" , :code => "CM02000047")
SalaryComJob.create(:title => "Program Director" , :code => "CM02000047")
SalaryComJob.create(:title => "TV/Radio Director" , :code => "CM02000047")
SalaryComJob.create(:title => "Film Editor" , :code => "CM02000048")
SalaryComJob.create(:title => "Tape Editor" , :code => "CM02000048")
SalaryComJob.create(:title => "Communications Representative I" , :code => "CM02000049")
SalaryComJob.create(:title => "Entry Level Communications Representative" , :code => "CM02000049")
SalaryComJob.create(:title => "Level I Communications Representative" , :code => "CM02000049")
SalaryComJob.create(:title => "Communications Representative II" , :code => "CM02000050")
SalaryComJob.create(:title => "Intermediate Level Communications Representative" , :code => "CM02000050")
SalaryComJob.create(:title => "Level II Communications Representative" , :code => "CM02000050")
SalaryComJob.create(:title => "Communications Representative III" , :code => "CM02000051")
SalaryComJob.create(:title => "Level III Communications Representative" , :code => "CM02000051")
SalaryComJob.create(:title => "Senior Level Communications Representative" , :code => "CM02000051")
SalaryComJob.create(:title => "Communications Editor I" , :code => "CM02000052")
SalaryComJob.create(:title => "Entry Level Communications Editor" , :code => "CM02000052")
SalaryComJob.create(:title => "Level I Communications Editor" , :code => "CM02000052")
SalaryComJob.create(:title => "Communications Editor II" , :code => "CM02000053")
SalaryComJob.create(:title => "Intermediate Level Communications Editor" , :code => "CM02000053")
SalaryComJob.create(:title => "Level II Communications Editor" , :code => "CM02000053")
SalaryComJob.create(:title => "Communications Editor III" , :code => "CM02000054")
SalaryComJob.create(:title => "Level III Communications Editor" , :code => "CM02000054")
SalaryComJob.create(:title => "Senior Level Communications Editor" , :code => "CM02000054")
SalaryComJob.create(:title => "Communications Editor - Project Lead" , :code => "CM02000055")
SalaryComJob.create(:title => "Communications Editor IV" , :code => "CM02000055")
SalaryComJob.create(:title => "Level IV Communications Editor" , :code => "CM02000055")
SalaryComJob.create(:title => "Communications Editor - Specialist" , :code => "CM02000056")
SalaryComJob.create(:title => "Communications Editor V" , :code => "CM02000056")
SalaryComJob.create(:title => "Level V Communications Editor" , :code => "CM02000056")
SalaryComJob.create(:title => "Communications Editing Supervisor" , :code => "CM02000057")
SalaryComJob.create(:title => "Communications Editor Supervisor" , :code => "CM02000057")
SalaryComJob.create(:title => "Communications Editing Manager" , :code => "CM02000058")
SalaryComJob.create(:title => "Communications Editor Manager" , :code => "CM02000058")
SalaryComJob.create(:title => "Publication General Manager" , :code => "CM02000059")
SalaryComJob.create(:title => "Publication Generalist Manager" , :code => "CM02000059")
SalaryComJob.create(:title => "Videographer" , :code => "CM02000060")
SalaryComJob.create(:title => "Photo Finishing Technician" , :code => "CM02000061")
SalaryComJob.create(:title => "Photo Lab Technician" , :code => "CM02000061")
SalaryComJob.create(:title => "Media Buyer" , :code => "CM02000062")
SalaryComJob.create(:title => "Media Planner" , :code => "CM02000063")
SalaryComJob.create(:title => "Print Production Coordinator" , :code => "CM02000064")
SalaryComJob.create(:title => "Managing Editor" , :code => "CM02000068")
SalaryComJob.create(:title => "Chapter Administrator" , :code => "CM02000069")
SalaryComJob.create(:title => "Chapter Relations Administrator" , :code => "CM02000069")
SalaryComJob.create(:title => "Chapter Relations Adminstrator" , :code => "CM02000069")
SalaryComJob.create(:title => "Lobbyist" , :code => "CM02000070")
SalaryComJob.create(:title => "Manager of Print Production" , :code => "CM02000071")
SalaryComJob.create(:title => "Print Production Manager" , :code => "CM02000071")
SalaryComJob.create(:title => "Grants and Proposals Manager" , :code => "CM02000072")
SalaryComJob.create(:title => "Grants/Proposal Manager" , :code => "CM02000072")
SalaryComJob.create(:title => "Grants/Proposal Writing Manager" , :code => "CM02000072")
SalaryComJob.create(:title => "Manager of Grants/Proposals" , :code => "CM02000072")
SalaryComJob.create(:title => "Proposal/Grant Manager" , :code => "CM02000072")
SalaryComJob.create(:title => "Level I Technical Writing Supervisor" , :code => "CM0200065")
SalaryComJob.create(:title => "Technical Writing Supervisor I" , :code => "CM0200065")
SalaryComJob.create(:title => "Level II Technical Writing Supervisor" , :code => "CM0200066")
SalaryComJob.create(:title => "Technical Writing Supervisor II" , :code => "CM0200066")
SalaryComJob.create(:title => "Level III Technical Writing Supervisor" , :code => "CM0200067")
SalaryComJob.create(:title => "Technical Writing Supervisor III" , :code => "CM0200067")
SalaryComJob.create(:title => "Manager of Technical Writing" , :code => "CM0200068")
SalaryComJob.create(:title => "Technical Writing Manager" , :code => "CM0200068")
SalaryComJob.create(:title => "Membership Manager" , :code => "CM0200069")
SalaryComJob.create(:title => "Memberships Manager" , :code => "CM0200069")
SalaryComJob.create(:title => "Fundraising Major Gifts Manager" , :code => "CM0200070")
SalaryComJob.create(:title => "Major Gift Manager" , :code => "CM0200070")
SalaryComJob.create(:title => "Major Gifts Manager" , :code => "CM0200070")
SalaryComJob.create(:title => "Member Certification Manager" , :code => "CM0200071")
SalaryComJob.create(:title => "Member Certifications Manager" , :code => "CM0200071")
SalaryComJob.create(:title => "Member Certification Specialist" , :code => "CM0200072")
SalaryComJob.create(:title => "Member Certifications Specialist" , :code => "CM0200072")
SalaryComJob.create(:title => "Member Records Administrator" , :code => "CM0200073")
SalaryComJob.create(:title => "Community Organizer" , :code => "CM0200074")
SalaryComJob.create(:title => "Community Outreach Worker" , :code => "CM0200074")
SalaryComJob.create(:title => "Director of Education" , :code => "CM0200075")
SalaryComJob.create(:title => "Education Director" , :code => "CM0200075")
SalaryComJob.create(:title => "Development Director" , :code => "CM0200076")
SalaryComJob.create(:title => "Director of Development" , :code => "CM0200076")
SalaryComJob.create(:title => "Development Manager" , :code => "CM0200077")
SalaryComJob.create(:title => "Manager of Development" , :code => "CM0200077")
SalaryComJob.create(:title => "Development Coordinator" , :code => "CM0200078")
SalaryComJob.create(:title => "Director of Membership" , :code => "CM0200079")
SalaryComJob.create(:title => "Membership Director" , :code => "CM0200079")
SalaryComJob.create(:title => "Memberships Director" , :code => "CM0200079")
SalaryComJob.create(:title => "Membership Assistant" , :code => "CM0200080")
SalaryComJob.create(:title => "Memberships Assistant" , :code => "CM0200080")
SalaryComJob.create(:title => "Curriculum Developer" , :code => "CM0200081")
SalaryComJob.create(:title => "Curriculum Specialist" , :code => "CM0200081")
SalaryComJob.create(:title => "Curriculum Specialist [Instructional Coordinators],CM0200081")
SalaryComJob.create(:title => "Instructional Designer,CM0200081")
SalaryComJob.create(:title => "Job Developer,CM0200082")
SalaryComJob.create(:title => "Job Coach,CM0200083")
SalaryComJob.create(:title => "Residential Couselor,CM0200083")
SalaryComJob.create(:title => "Residential Living Assistant,CM0200083")